export enum Lang {
  Bulgarian = "bg",
  Czech = "cs",
  Danish = "da",
  Dutch = "nl",
  English = "en",
  Estonian = "et",
  Finnish = "fi",
  French = "fr",
  German = "de",
  Greek = "el",
  Hungarian = "hu",
  Italian = "it",
  Latvian = "lv",
  Lithuanian = "lt",
  Norwegian = "no",
  Polish = "pl",
  Portuguese = "pt",
  Romanian = "ro",
  Russian = "ru",
  Serbian = "sr",
  Slovak = "sk",
  Slovenian = "sl",
  Spanish = "es",
  Swedish = "sv",
  Turkish = "tr"
}
